// <auto-generated />
namespace BusinessRequirements.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _002MigrationHLC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_002MigrationHLC));
        
        string IMigrationMetadata.Id
        {
            get { return "202012311958593_002Migration/HLC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
